# VELOCITY-X Workflow Configuration
# 워크플로우별 실행 순서 및 설정

version: "1.0.0"

workflows:
  quality-trio:
    name: "Quality Trio MVP"
    description: "Polish + Review + Test 에이전트 워크플로우"
    agents:
      - velocity-x-polish-specialist
      - velocity-x-code-reviewer
      - velocity-x-test-engineer
    
  security-focused:
    name: "Security Focused Workflow"
    description: "보안 중심 워크플로우"
    agents:
      - velocity-x-polish-specialist
      - velocity-x-security-guardian
      - velocity-x-code-reviewer
      - velocity-x-test-engineer
      
  full-workflow:
    name: "Full VELOCITY-X Workflow"
    description: "전체 9개 에이전트 워크플로우"
    agents:
      - velocity-x-vibe-specialist
      - velocity-x-flow-specialist
      - velocity-x-polish-specialist
      - velocity-x-security-guardian
      - velocity-x-code-reviewer
      - velocity-x-test-engineer
      - velocity-x-ui-architect
      - velocity-x-performance-optimizer
      - velocity-x-documentation-scribe

# 실행 설정
execution:
  max_parallel_agents: 2
  default_timeout: 300
  retry_attempts: 2
  log_level: "INFO"